### ISSUE TITLE
[Feature] PlaceHolder condition

### ISSUE THREAD

**Issue by tiradorus** [Eniripsa96/SkillAPIKotlin#24]
I know it's abit strange, but with a global "placeholder condition" you could add many and many conditions that scale on other plugins.

Some examples:

```
Condition:
  Placeholder: %server_time_MMM%
  Value: Jan

Make the skill usabe only on January
```

```
Condition:
  Placeholder: %objective_score_Light%
  Value: 15

Make the skill usabe only if the player have the ScoreBoard "Light" to 15
```

```
Condition:
  Placeholder: %factions_powermax%
  Value: 23

Make the skill usabe only if the player have a 23 max Power from the plugin "Factions"
```

```
Condition:
  Placeholder: %quests_player_has_current_quest_exampleQuest%
  Value: true

Make the skill usabe only if the player have the quest "exampleQuest" from the plugin "Quests"
```

Etc etc.

You could create as much conditions as you want just with placeholder, and it add a large compatibility from SkillApi to every other plugins that use placeholders!
